name: terraform-aws-elk-observability

on:
  push:
    branches: [ "**" ] 

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-central-1" 
      TF_VAR_admin_ip: ${{ secrets.ADMIN_IP }}
      TF_VAR_db_user: ${{ secrets.DB_USER }}
      TF_VAR_db_pass: ${{ secrets.DB_PASS }}
      TF_VAR_elastic_password: ${{ secrets.ELASTIC_PASSWORD}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./infra

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra
        
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra

      - name: Terraform Apply
        #This step ll be just executed if working in main
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ./infra